### ISSUE TITLE
Create a proper package

### ISSUE THREAD

**Issue by SebastianCallh** [SebastianCallh/IterGP.jl#4]
Currently the repo is in a very ad hoc state. We want to package it up to make it usable for others. 

Tasks:
- Package properly with a UUID
- Move code to src/IterGP.jl and other src/*.jl
- Add tests for different strategies not crashing and converging
- Move example scripts to examples/* with custom envs

**Comment by sethaxen** [comment]
This seems to be mostly finished now, except that the `Project.toml` lists the package as IterGPs with an _s_ at the end. I think IterGP like the Python package and the repo name makes more sense.

**Comment by SebastianCallh** [comment]
Thank you so much for taking the time to look at this package and open issues @sethaxen ! 

Easy enough to fix. But doesn't it make more sense to name the packege `IterGPs` to be more consistent with `AbstractGPs` and the  rest of the JuliaGaussianProcess names? As far as I understand, naming the module `IterGP` will also introduce a name collision with the `IterGP` struct. Thoughts?

**Comment by sethaxen** [comment]
> Thank you so much for taking the time to look at this package and open issues @sethaxen !

No problem!

> But doesn't it make more sense to name the packege `IterGPs` to be more consistent with `AbstractGPs` and the rest of the JuliaGaussianProcess names?

I think either works. In my opinion, consistency in naming with the JuliaGPs ecosystem is not necessary. In my view it depends on what the intended scope of this package is. If it is trying to represent all GPs that might be produced by using iterative solvers for GP inference, then `IterGPs` makes sense. But if it is focusing on providing the IterGP method, then I think the name `IterGP` makes more sense, which is defined in the paper and repo as describing the method, not the GPs themselves.

> As far as I understand, naming the module `IterGP` will also introduce a name collision with the `IterGP` struct

Yes, that's right. Although, as noted above, in my view "IterGP" describes the class of methods, not the GP itself. So I actually think a nonexported `IterGP.Posterior` or a possible-exported `IterGP.IterGPPosterior` makes more sense, which would remove any name conflict. For reference. the itergp package returns a `ConditionalPosterior` object.

**Comment by SebastianCallh** [comment]
Those are good points. The scope should most certainly be implementing the `IterGP` proposed in the paper, so that settles the naming discussion. What do you think about https://github.com/SebastianCallh/IterGP.jl/pull/10?
